### PR TITLE
Travis ci

### PR DESCRIPTION
**Pull request by WeatherGod**
I have no clue if this will work...

### CODE REVIEW

**Comment by WeatherGod** [comment]
@mdboom, @tacaswell , I don't think I have the necessary permissions with this group to add basemap to the approved list for TravisCI: https://travis-ci.org/matplotlib

**Comment by tacaswell** [comment]
Turned on, next push should run.

**Comment by tacaswell** [comment]
I merged this so that if the next thing that hits is a different PR it won't automatically fail.

**Comment by QuLogic** [comment]
Failed to build, unfortunately. Apparently, you forgot to install matplotlib?

**Comment by WeatherGod** [comment]
Ah, apparently I forgot that basemap isn't using setuptools and won't automatically install dependencies. I'll make a new PR and we can see if this works next time.

**Pull request merged**
