### PR TITLE
arcgisimage() wmsimage() should use print function

### PR DESCRIPTION
**Pull request by micahcochran**
Changes the code to use Python 3.x print functions instead of print statements.

Found this when I was playing with nose and nose2.

### CODE REVIEW

**Comment by WeatherGod** [comment]
Just so you know, the entire codebase goes through 2to3 as part of the
installation process for python3 environments. Not ideal, but it works.

**Comment by micahcochran** [comment]
Ahh that makes more sense now.

test.py for Travis isn't getting the 2to3 treatment.

I don't think there is any ideal way to support Python 2 and 3, just less bad ways.

**Comment by micahcochran** [comment]
Should I close this as a useless PR?

**Comment by jenshnielsen** [comment]
I think it's fine to convert the print statements to functions even if the code goes through 2to3. We should just add a `from __future__ import print_function` at the top too. 

It would be preferable to fully convert the code to use six or similar rather than 2to3 but thats a larger task

**Comment by micahcochran** [comment]
2to3 will just strip out the `from __future import ...` statements.  If that is the future goal, then there is no time like the present to begin that change.

**Comment by WeatherGod** [comment]
While I appreciate the enthusiasm, I would like to first direct that energy
towards building up the test suite. That test suite will be critical before
doing any sort of massive overhaul of the codebase.

**Comment by micahcochran** [comment]
@WeatherGod I understand.  It is not a problem.

I do have some questions about expanding the unitests, but I will open an issue about that.

**Comment by micahcochran** [comment]
Unneeded. Closing.

**Pull request closed without merging**
