### PR TITLE
Update geos version number

### PR DESCRIPTION
**Pull request by joernu76**
Fix issue #496

### CODE REVIEW

**Comment by joernu76** [comment]
I removed 2.6, but kept 2.7 for now. I also added python 3.7+3.8 but removed 3.4 and 3.5.

Now the tests would likely pass when issue #495 would be adressed (all failing test cases show the "dedent" failure.

When accepting this and the #495 fix, travis will likely suceed, otherwise I can have another look.

**Comment by WeatherGod** [comment]
Going to power-cycle the PR to see how it holds up now that I accepted #496.

**Comment by WeatherGod** [comment]
Looks like something isn't right with libgeos v3.6.1. We are getting a segfault during the tests.

**Comment by joernu76** [comment]
Why did the tests not segfault in the pipeline for my merge request?

**Comment by joernu76** [comment]
Ah, because the dedent was fixed.
Will see what I can do to fix this.

**Comment by joernu76** [comment]
The tests pass now. There was a "closed" issue pointing out this exact error. I modified the solution slightly. GEOS doesn't accept infinites any more and I added a workaround for this that has likely no implications. I do not fully understand the code at that point in time though. The fix cannot be worse than the crash, though...

**Comment by WeatherGod** [comment]
And you see why I want to dump this codebase like the hot mess that it is?

Yeah, this fix looks reasonable, but it makes me worry that there are similar issues elsewhere in the codebase. The unit tests aren't nearly extensive enough. I am going to put it though some more paces by having it generate the documentation on my machine as well.

**Comment by WeatherGod** [comment]
The examples are reminding me why I have been wanting to drop this library for so long, as some of them are broken for various reasons, but most are fine, and nothing seems broken by this fix, so it should be a net improvement. Merging.

**Pull request merged**
