### PR TITLE
fix for DeprecationWarning: using a non-integer

### PR DESCRIPTION
**Pull request by micahcochran**
Fixes these deprecation warnings from unitest in the TestShiftGrid class:
> test_cyc (__main__.TestShiftGrid) ... lib/mpl_toolkits/basemap/test.py:93: DeprecationWarning: using a non-integer number instead of an integer will result in an error in the future

~~This was done by changing the numpy arrays datatype from float to int.~~

### CODE REVIEW

**Comment by micahcochran** [comment]
Premature pull request.  Sorry.  Closing.

**Comment by QuLogic** [comment]
FYI, you can update the branch and the PR will be updated; it's not necessary to close a WIP (unless you started with `master` branch because that's tricky.)

**Comment by micahcochran** [comment]
Thanks @QuLogic .

It was actually an Warning caused by passing a float to the index of the numpy array.  In the development version of numpy, it causes an IndexError.

I am reopening this.

**Comment by micahcochran** [comment]
I'm ready for this PR to be merged.  Is there a good reason not to merge?

**Comment by WeatherGod** [comment]
I had completely forgotten about this. I can't remember what the hold-up was, but looking at the change, I don't think that this doesn't completely solve the problem. The result of `a//b` is still a float, so the result still needs to be cast to an integer, I think.

**Comment by jenshnielsen** [comment]
@WeatherGod I don't think so 
```
3//2 = 1 
3.0//2 = 1.0
```
but len(lonin) should be an integer.

**Comment by WeatherGod** [comment]
is that true in py3k? (I don't have a py3k environment on me at work)

**Comment by jenshnielsen** [comment]
Yes that's the same in 3.5

**Comment by WeatherGod** [comment]
Okie-doky, then.

**Comment by micahcochran** [comment]
Thanks @WeatherGod and @jenshnielsen

**Pull request merged**
